version: '3.7'
services:
  jenkins:
    build: .
    container_name: jenkins
    networks:
      - ci-network
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Permitir acceso al Docker del host
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root  # Ejecutar Jenkins como root para evitar problemas de permisos
    privileged: true  # Dar acceso completo al sistema para manipular Docker

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    networks:
      - ci-network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true  # Desactiva comprobaciones en entornos locales

volumes:
  jenkins_home:
  sonarqube_data:

networks:
  ci-network:
    driver: bridge
